### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by lucasgrelaud** [takuyakun/ummey#4]
Hi,
I noticed you've left sensitive information in the following file;
 - [AWS S3 credentials](https://github.com/takuyakun/ummey/blob/master/config/initializers/carrier_wave.rb)

This may lead to a security issue in your app, so you should remove these informations from your repository.

Regards,
Lucas GRELAUD

**Comment by takuyakun** [comment]
Wow, thank you!
Should I delete commit log?

**Comment by lucasgrelaud** [comment]
If you can, definitly.

**Comment by takuyakun** [comment]
I can't delete commit log...

**Comment by takuyakun** [comment]
> If you can, definitly.
I can't delete commit log...
